# Cargo config file

# Environment variables
[env]

## Secrets
# Contraseñas para desarrollo en localhost

SERVICE_DB_URL = "postgres://app_user:dev_only_pwd@localhost/app_db"

# Scope down traceing, to filter out external lib tracing
RUST_LOG="rust_web_app=debug"
SERVICE_WEB_FOLDER="web-folder/"