version: '3.8'

services:
  client:
    build: 
      context: ./
      dockerfile: client/GestorDocumental/Dockerfile
    container_name: angular_client
    volumes:
    - ./client/GestorDocumental:/src/app
    ports:
      - "3400:4200"
    depends_on:
      - app

  app:
    build: 
      context: ./
      dockerfile: server/Dockerfile
    container_name: rust_app
    volumes:
      - ./server:/src/server
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:54328/mydatabase

  db:
    build:
      context: ./
      dockerfile: database/Dockerfile
    container_name: postgres_db
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: gestor_documental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "54328:5432"


  
